# Generated by Django 4.2 on 2024-02-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254, verbose_name='email address'
            ),
        ),
    ]
