# Generated by Django 4.2 on 2024-01-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Введите название товара',
                        max_length=100,
                        verbose_name='название',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Введите описание товара',
                        max_length=1000,
                        verbose_name='описание',
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Введите цену товара',
                        max_digits=15,
                        verbose_name='цена',
                    ),
                ),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
