# Generated by Django 4.2 on 2024-01-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='Введите описание товара',
                max_length=1000,
                null=True,
                verbose_name='описание',
            ),
        ),
    ]
