# Generated by Django 4.2 on 2024-02-07 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='Пользователь, создавший товар',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='products',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
